# root権限で実行
sudo: required

services: docker

#docker-composeを立ち上げ
before_install:
  - docker-compose up --build -docker -d

# DBを準備
script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test

